version: '3.7'

services:

  bot:
    build: .
    ports:    # <= --publish
      - "4001:4001"
    volumes:
      - ./app:/home/app
      - mix_cache:/root/.mix
    links:
      - bot_db
    container_name: bot

  bot_db:
    image: postgres:11-alpine
    container_name: bot_db

volumes:
  mix_cache: